---
name: Amazon S3 Backup
version: dev
slug: amazon-s3-backup
description: "Sync Backups to your Amazon S3 bucket"
url: "https://github.com/RemCom/hass-addons"
codenotary: dev@remcom.dev
init: false
hassio_api: true
hassio_role: homeassistant
arch:
  - aarch64
  - amd64
  - armv7
map:
  - addon_config:rw
  - backup:rw
options:
  aws_access_key": ""
  aws_secret_access_key": ""
  bucket_name": ""
  bucket_region": "eu-west-1"
  storage_class": "STANDARD"
  delete_local_backups": false
  local_backups_to_keep": 3
schema:
  aws_access_key": str
  aws_secret_access_key": password
  bucket_name": str
  # yamllint disable-line rule:line-length
  bucket_region": list(us-east-1|us-east-2|us-west-1|us-west-2|ca-central-1|eu-north-1|eu-west-1|eu-central-1|eu-west-2|eu-west-3|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|sa-east-1)
  # yamllint disable-line rule:line-length
  storage_class": list(STANDARD|REDUCED_REDUNDANCY|STANDARD_IA|ONEZONE_IA|INTELLIGENT_TIERING|GLACIER|DEEP_ARCHIVE)
  delete_local_backups": bool
  local_backups_to_keep": int
